### ISSUE TITLE
Milestone: Alpha

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/wine-search#2]
[Milestone]: https://github.com/UCDavisLibrary/wine-search/milestone/1
[Alpha Website]: https://wine-search-dev.library.ucdavis.edu 

This Milestone relates to making public access to the the initial version of the wine-search  application.  
The first version only includes data from the PTV marks. Some of the items are addressed below.  You can also review the complete [Milestone].

- [x] Review UI design 
- [x] Setup proper dev/test for production location #3 
- [x] Get a proper DNS name / Search API and html on same site? #3 
- [x] Determine the number of times and method to keep elastic search up to date
- [x] Standardize our country codes #4 
- [x] Verify we have enough information on the bottle_info #8
The current UI designs can be found in the [Google Drive Folder](https://drive.google.com/open?id=0B4y2_Xs4SL2-bW9wUFdnbFN2RW8) these are illustrator files, but are previewed.

# Completion

This milestone is considered complete when the [Alpha Website] https://wine-search-dev.library.ucdavis.edu is working, and reasonably close to the UI design.

**Comment by jrmerz** [comment]
@qjhart we still have some 'pixel perfect tweaks' #16 but I would say the deployed version at [wine-search-dev](http://wine-search-dev.library.ucdavis.edu) is now a suitable alpha.

**Comment by qjhart** [comment]
@pbrantley / @NeilWeingarten / @amyazzarito https://wine-search-dev.library.ucdavis.edu/ is now up and running as the alpha setup.  If you'd like this moved to another location (eg. wine-search.library.ucdavis.edu). Reopen.

Yeah!
